/*
 *  Sound.h
 *  AudioFeatures
 *
 *  Created by Nick Collins on 01/08/2007.
 *  Copyright 2007 Nick Collins. All rights reserved.
 *
 */

#pragma once

//817 audio files
const char *strings[] = {
    
    "/data/audio/mirdata/EMcorpus/PeterManning/A Noite, Porem, Rangeu E Quebrou.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Beachcombers.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Bins And Bells.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Kettle And Cans.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Tins And Tanks.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Buckets And Bolts.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Pots And Pans.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Centoph.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Dreamfile.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Hunt, Jerry_ Fluud for dual Syncl.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Everything Goes When The Whistle.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Chor Der Waisen.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Still Hidden Laughs.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/I Tol D. You So.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/sunSurgeAutomata.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Wasting.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Contraption.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Still Life With Piano.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Martin Butler.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Elmore.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Approximate Rhythms.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Just-More-Idle-Chatter.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Quadro.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Memory Pages.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Notjustmoreidlechatter.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/The Lesson.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Word Color.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Idle Chatter.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Erosphere.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Puzzlasept.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Bocalises.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/D'un Jardin À L'Autre.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Suite N.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/L'invitation Au Départ.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/La Ronde.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/La Roue Ferris.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Touch - Part I.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Touch - Part II.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Expo '85 for multiple synthesizer part1.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Expo '85 for multiple synthesizer part2.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Expo '85 for multiple synthesizer part3.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Expo '85 for multiple synthesizer part4.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Sud (A).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Sud (B).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Sud (C).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Dialogues.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Inharmonique.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Mutations.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Joel Chadabe _ Modalities.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Neil Rolnick & Kathleen Myers _ R.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Neil Rolnick _ A Robert Johnson S.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Carter Scholz _ Oliveros_ Lion's.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Julie Kabat & Neil Rolnick _ Kaba.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Barton McLean _ A Little Night Mu.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Barton McLean _ Demons Of The Nig.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/I Am Sitting In A Room.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Medieval Purity In A Bed Of Thorn.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/With Fish Scales Scattered.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Contours, Clowns And Shadows.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Strings Of Token Strings (1984).wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Nonet_ Computer Music In Four Tra.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Syntax.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Kaleidocycles.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/What Is The Use_.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Lady Neil's Dumpe.wav",
    "/data/audio/mirdata/EMcorpus/PeterManning/Gole